# Generated by Django 3.2.8 on 2023-12-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='question',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='address',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phonenumber',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
